name: SurvivalGamesV3
main: SurvivalGamesV3\SurvivalGamesV3
version: 3.0.1
api: 2.0.0
author: ImagicalGamer


commands:
    sg:
        usage: /sg make
        description: SurvivalGames-Commands
